
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Aug 25 00:35:39 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 13;
  public static final int CHAR = 51;
  public static final int CONST = 5;
  public static final int EQUALS = 8;
  public static final int LPAREN = 17;
  public static final int SEMI = 6;
  public static final int CONTINUE = 23;
  public static final int FORANY = 10;
  public static final int MINUS = 32;
  public static final int RPAREN = 18;
  public static final int AND = 31;
  public static final int LS = 38;
  public static final int OR = 30;
  public static final int BOOL = 48;
  public static final int COMMA = 7;
  public static final int CLASS = 15;
  public static final int LSE = 39;
  public static final int INC = 28;
  public static final int DIV = 42;
  public static final int DOUBLEDOT = 11;
  public static final int DIFFERENT = 35;
  public static final int PLUS = 40;
  public static final int IF = 20;
  public static final int DOT = 26;
  public static final int FINDANY = 46;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int RBRACKET = 14;
  public static final int NEW = 33;
  public static final int error = 1;
  public static final int ISEQUAL = 34;
  public static final int MUL = 41;
  public static final int MODIFOP = 12;
  public static final int NUMBER = 49;
  public static final int MOD = 43;
  public static final int IDENT = 50;
  public static final int BREAK = 22;
  public static final int VOID = 19;
  public static final int GTE = 37;
  public static final int ARROW = 27;
  public static final int FOREACH = 45;
  public static final int LBRACE = 3;
  public static final int ELSE = 9;
  public static final int READ = 25;
  public static final int WHILE = 21;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int DEC = 29;
  public static final int GT = 36;
  public static final int PRINT = 44;
  public static final int FINDANDREPLACE = 47;
}

